# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Tipo de Escuelas
    submenu:
      - name: Gamer
        link: /projects/gamer
      - name: Conducción
        link: /projects/conducción
  - name: Posts
    link: /
  - name: Secundarias
    link: /secundarias
  - name: Bachilleres
    link: /bachilleres
  - name: Contacto
 link: /contacto
  
   
    
